### ISSUE TITLE
[1.17] Server Startup Crash

### ISSUE THREAD

**Issue by VaelophisNyx** [makubas/better-ladders#1]
[latest.log](https://github.com/makubas/better-ladders/files/6705681/latest.log)
this log file contains the crash, mentioning what I assume is this mod, as "betlad"

**Comment by CanadianBaconBoi** [comment]
This is because it relies on `net/minecraft/class_310` or `MinecraftClient`, nothing we can do about it unless someone wants to make a PR or the mod author fixes it themselves.

**Comment by jakubwesta** [comment]
@CanadianBaconBoi fixed it. Sorry that I didn't see that issue. I will upload the new version on curseforge in a few hours.
